stages:
- test-openshift

plone-openshift:
  tags:
  - openshift
  image: docker.git.imsweb.com/plone/buildout-configs/plone-testrunner:latest
  stage: test-openshift
  before_script:
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_PROJECT_PATH
  script:
  - echo $CI_PROJECT_NAMESPACE
  - echo $CI_REGISTRY
  - echo $CI_PROJECT_PATH
  - echo "Activating Source installing setuptools and buildout"
  - source /plone5/instance/bin/activate
  - echo "Install Successful"
  - echo "Running buildout"
  - buildout -c gitlab-ci.cfg
  - echo "buildout successful"
  - echo "running test on version:"
  - python setup.py --version
  - /builds/$CI_PROJECT_PATH/bin/test -v -s ims.fieldupdater
